version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - yum install -y nginx git unzip || true

  pre_build:
    commands:
      - echo "Pre-build started"

  build:
    commands:
      - echo "Build complete"

  post_build:
    commands:
      - echo "Post-build complete"

artifacts:
  base-directory: terraform/dev/cicd_assets
  files:
    - appspec.yml
    - scripts/**/*

cache:
  paths:
    - '/root/.cache/pip/**/*'
